name: Build and Deploy NestJs app to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: hunns-rsvp
  AZURE_WEBAPP_PACKAGE_PATH: ./backend
  NODE_VERSION: "18.x"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Set up Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: npm install and build
        run: |
          npm install
          npm run build --if-present
        working-directory: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      - name: Compress files for deployment
        shell: pwsh # Specify PowerShell shell for this step
        run: |
          $sourcePath = "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"
          $destinationZip = "nest.zip"

          $filesToZip = Get-ChildItem -Path $sourcePath -Recurse `
              | Where-Object { 
                  $_.FullName -notmatch "test" -and
                  $_.FullName -notmatch "src" -and
                  $_.FullName -notmatch "\.git" -and
                  $_.Extension -ne ".md"
              }

          $filesToZip | Compress-Archive -DestinationPath $destinationZip

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: nest.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: "Deploy to Azure Web App"
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: "Production"
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_BACKEND }}
          package: nest.zip

      - name: Delete zip file
        run: rm nest.zip
